/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef THRIFT_RPC_TYPES_H
#define THRIFT_RPC_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>

/* custom thrift includes */

/* begin types */

/* struct Peer */
struct _ThriftPeer
{ 
  ThriftStruct parent; 

  /* public */
  gchar * host;
  gint32 port;
};
typedef struct _ThriftPeer ThriftPeer;

struct _ThriftPeerClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftPeerClass ThriftPeerClass;

GType thrift_peer_get_type (void);
#define THRIFT_TYPE_PEER (thrift_peer_get_type())
#define THRIFT_PEER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_PEER, ThriftPeer))
#define THRIFT_PEER_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_PEER, ThriftPeerClass))
#define THRIFT_IS_PEER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_PEER))
#define THRIFT_IS_PEER_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_PEER))
#define THRIFT_PEER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_PEER, ThriftPeerClass))

/* struct BucketValue */
struct _ThriftBucketValue
{ 
  ThriftStruct parent; 

  /* public */
  gint64 search_key;
  GByteArray * value;
};
typedef struct _ThriftBucketValue ThriftBucketValue;

struct _ThriftBucketValueClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftBucketValueClass ThriftBucketValueClass;

GType thrift_bucket_value_get_type (void);
#define THRIFT_TYPE_BUCKET_VALUE (thrift_bucket_value_get_type())
#define THRIFT_BUCKET_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_BUCKET_VALUE, ThriftBucketValue))
#define THRIFT_BUCKET_VALUE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_BUCKET_VALUE, ThriftBucketValueClass))
#define THRIFT_IS_BUCKET_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_BUCKET_VALUE))
#define THRIFT_IS_BUCKET_VALUE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_BUCKET_VALUE))
#define THRIFT_BUCKET_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_BUCKET_VALUE, ThriftBucketValueClass))

/* struct Bucket */
struct _ThriftBucket
{ 
  ThriftStruct parent; 

  /* public */
  gint64 search_key_min;
  gint64 search_key_max;
  GPtrArray * values;
  gboolean __isset_values;
};
typedef struct _ThriftBucket ThriftBucket;

struct _ThriftBucketClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftBucketClass ThriftBucketClass;

GType thrift_bucket_get_type (void);
#define THRIFT_TYPE_BUCKET (thrift_bucket_get_type())
#define THRIFT_BUCKET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_BUCKET, ThriftBucket))
#define THRIFT_BUCKET_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_BUCKET, ThriftBucketClass))
#define THRIFT_IS_BUCKET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_BUCKET))
#define THRIFT_IS_BUCKET_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_BUCKET))
#define THRIFT_BUCKET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_BUCKET, ThriftBucketClass))

/* struct BucketKeys */
struct _ThriftBucketKeys
{ 
  ThriftStruct parent; 

  /* public */
  gint64 search_key_min;
  gint64 search_key_max;
};
typedef struct _ThriftBucketKeys ThriftBucketKeys;

struct _ThriftBucketKeysClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftBucketKeysClass ThriftBucketKeysClass;

GType thrift_bucket_keys_get_type (void);
#define THRIFT_TYPE_BUCKET_KEYS (thrift_bucket_keys_get_type())
#define THRIFT_BUCKET_KEYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_BUCKET_KEYS, ThriftBucketKeys))
#define THRIFT_BUCKET_KEYS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_BUCKET_KEYS, ThriftBucketKeysClass))
#define THRIFT_IS_BUCKET_KEYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_BUCKET_KEYS))
#define THRIFT_IS_BUCKET_KEYS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_BUCKET_KEYS))
#define THRIFT_BUCKET_KEYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_BUCKET_KEYS, ThriftBucketKeysClass))

struct _ThriftStorageException
{ 
  ThriftStruct parent; 

  /* public */
  gint32 error_code;
  gchar * error_message;
};
typedef struct _ThriftStorageException ThriftStorageException;

struct _ThriftStorageExceptionClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftStorageExceptionClass ThriftStorageExceptionClass;

GType thrift_storage_exception_get_type (void);
#define THRIFT_TYPE_STORAGE_EXCEPTION (thrift_storage_exception_get_type())
#define THRIFT_STORAGE_EXCEPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_STORAGE_EXCEPTION, ThriftStorageException))
#define THRIFT_STORAGE_EXCEPTION_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_STORAGE_EXCEPTION, ThriftStorageExceptionClass))
#define THRIFT_IS_STORAGE_EXCEPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_STORAGE_EXCEPTION))
#define THRIFT_IS_STORAGE_EXCEPTION_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_STORAGE_EXCEPTION))
#define THRIFT_STORAGE_EXCEPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_STORAGE_EXCEPTION, ThriftStorageExceptionClass))

/* exception */
typedef enum
{
  THRIFT_STORAGE_EXCEPTION_ERROR_CODE
} ThriftStorageExceptionError;

GQuark thrift_storage_exception_error_quark (void);
#define THRIFT_STORAGE_EXCEPTION_ERROR (thrift_storage_exception_error_quark())


/* constants */

/* struct RpcFindClosestPeersArgs */
struct _ThriftRpcFindClosestPeersArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
};
typedef struct _ThriftRpcFindClosestPeersArgs ThriftRpcFindClosestPeersArgs;

struct _ThriftRpcFindClosestPeersArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcFindClosestPeersArgsClass ThriftRpcFindClosestPeersArgsClass;

GType thrift_rpc_find_closest_peers_args_get_type (void);
#define THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_ARGS (thrift_rpc_find_closest_peers_args_get_type())
#define THRIFT_RPC_FIND_CLOSEST_PEERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_ARGS, ThriftRpcFindClosestPeersArgs))
#define THRIFT_RPC_FIND_CLOSEST_PEERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_FIND_CLOSEST_PEERS_ARGS, ThriftRpcFindClosestPeersArgsClass))
#define THRIFT_IS_RPC_FIND_CLOSEST_PEERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_ARGS))
#define THRIFT_IS_RPC_FIND_CLOSEST_PEERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_ARGS))
#define THRIFT_RPC_FIND_CLOSEST_PEERS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_ARGS, ThriftRpcFindClosestPeersArgsClass))

/* struct RpcFindClosestPeersResult */
struct _ThriftRpcFindClosestPeersResult
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * success;
  gboolean __isset_success;
};
typedef struct _ThriftRpcFindClosestPeersResult ThriftRpcFindClosestPeersResult;

struct _ThriftRpcFindClosestPeersResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcFindClosestPeersResultClass ThriftRpcFindClosestPeersResultClass;

GType thrift_rpc_find_closest_peers_result_get_type (void);
#define THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_RESULT (thrift_rpc_find_closest_peers_result_get_type())
#define THRIFT_RPC_FIND_CLOSEST_PEERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_RESULT, ThriftRpcFindClosestPeersResult))
#define THRIFT_RPC_FIND_CLOSEST_PEERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_FIND_CLOSEST_PEERS_RESULT, ThriftRpcFindClosestPeersResultClass))
#define THRIFT_IS_RPC_FIND_CLOSEST_PEERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_RESULT))
#define THRIFT_IS_RPC_FIND_CLOSEST_PEERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_RESULT))
#define THRIFT_RPC_FIND_CLOSEST_PEERS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_FIND_CLOSEST_PEERS_RESULT, ThriftRpcFindClosestPeersResultClass))

/* struct RpcFindKeyArgs */
struct _ThriftRpcFindKeyArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * ident;
  gboolean __isset_ident;
  gint64 search_key;
  gboolean __isset_search_key;
};
typedef struct _ThriftRpcFindKeyArgs ThriftRpcFindKeyArgs;

struct _ThriftRpcFindKeyArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcFindKeyArgsClass ThriftRpcFindKeyArgsClass;

GType thrift_rpc_find_key_args_get_type (void);
#define THRIFT_TYPE_RPC_FIND_KEY_ARGS (thrift_rpc_find_key_args_get_type())
#define THRIFT_RPC_FIND_KEY_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_FIND_KEY_ARGS, ThriftRpcFindKeyArgs))
#define THRIFT_RPC_FIND_KEY_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_FIND_KEY_ARGS, ThriftRpcFindKeyArgsClass))
#define THRIFT_IS_RPC_FIND_KEY_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_FIND_KEY_ARGS))
#define THRIFT_IS_RPC_FIND_KEY_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_FIND_KEY_ARGS))
#define THRIFT_RPC_FIND_KEY_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_FIND_KEY_ARGS, ThriftRpcFindKeyArgsClass))

/* struct RpcFindKeyResult */
struct _ThriftRpcFindKeyResult
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * success;
  gboolean __isset_success;
  ThriftStorageException * err;
  gboolean __isset_err;
};
typedef struct _ThriftRpcFindKeyResult ThriftRpcFindKeyResult;

struct _ThriftRpcFindKeyResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcFindKeyResultClass ThriftRpcFindKeyResultClass;

GType thrift_rpc_find_key_result_get_type (void);
#define THRIFT_TYPE_RPC_FIND_KEY_RESULT (thrift_rpc_find_key_result_get_type())
#define THRIFT_RPC_FIND_KEY_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_FIND_KEY_RESULT, ThriftRpcFindKeyResult))
#define THRIFT_RPC_FIND_KEY_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_FIND_KEY_RESULT, ThriftRpcFindKeyResultClass))
#define THRIFT_IS_RPC_FIND_KEY_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_FIND_KEY_RESULT))
#define THRIFT_IS_RPC_FIND_KEY_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_FIND_KEY_RESULT))
#define THRIFT_RPC_FIND_KEY_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_FIND_KEY_RESULT, ThriftRpcFindKeyResultClass))

/* struct RpcGetBucketKeysArgs */
struct _ThriftRpcGetBucketKeysArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
};
typedef struct _ThriftRpcGetBucketKeysArgs ThriftRpcGetBucketKeysArgs;

struct _ThriftRpcGetBucketKeysArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetBucketKeysArgsClass ThriftRpcGetBucketKeysArgsClass;

GType thrift_rpc_get_bucket_keys_args_get_type (void);
#define THRIFT_TYPE_RPC_GET_BUCKET_KEYS_ARGS (thrift_rpc_get_bucket_keys_args_get_type())
#define THRIFT_RPC_GET_BUCKET_KEYS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_ARGS, ThriftRpcGetBucketKeysArgs))
#define THRIFT_RPC_GET_BUCKET_KEYS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_BUCKET_KEYS_ARGS, ThriftRpcGetBucketKeysArgsClass))
#define THRIFT_IS_RPC_GET_BUCKET_KEYS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_ARGS))
#define THRIFT_IS_RPC_GET_BUCKET_KEYS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_ARGS))
#define THRIFT_RPC_GET_BUCKET_KEYS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_ARGS, ThriftRpcGetBucketKeysArgsClass))

/* struct RpcGetBucketKeysResult */
struct _ThriftRpcGetBucketKeysResult
{ 
  ThriftStruct parent; 

  /* public */
  ThriftBucketKeys * success;
  gboolean __isset_success;
  ThriftStorageException * err;
  gboolean __isset_err;
};
typedef struct _ThriftRpcGetBucketKeysResult ThriftRpcGetBucketKeysResult;

struct _ThriftRpcGetBucketKeysResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetBucketKeysResultClass ThriftRpcGetBucketKeysResultClass;

GType thrift_rpc_get_bucket_keys_result_get_type (void);
#define THRIFT_TYPE_RPC_GET_BUCKET_KEYS_RESULT (thrift_rpc_get_bucket_keys_result_get_type())
#define THRIFT_RPC_GET_BUCKET_KEYS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_RESULT, ThriftRpcGetBucketKeysResult))
#define THRIFT_RPC_GET_BUCKET_KEYS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_BUCKET_KEYS_RESULT, ThriftRpcGetBucketKeysResultClass))
#define THRIFT_IS_RPC_GET_BUCKET_KEYS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_RESULT))
#define THRIFT_IS_RPC_GET_BUCKET_KEYS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_RESULT))
#define THRIFT_RPC_GET_BUCKET_KEYS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_BUCKET_KEYS_RESULT, ThriftRpcGetBucketKeysResultClass))

/* struct RpcPutArgs */
struct _ThriftRpcPutArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
  GByteArray * value;
  gboolean __isset_value;
};
typedef struct _ThriftRpcPutArgs ThriftRpcPutArgs;

struct _ThriftRpcPutArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcPutArgsClass ThriftRpcPutArgsClass;

GType thrift_rpc_put_args_get_type (void);
#define THRIFT_TYPE_RPC_PUT_ARGS (thrift_rpc_put_args_get_type())
#define THRIFT_RPC_PUT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_PUT_ARGS, ThriftRpcPutArgs))
#define THRIFT_RPC_PUT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_PUT_ARGS, ThriftRpcPutArgsClass))
#define THRIFT_IS_RPC_PUT_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_PUT_ARGS))
#define THRIFT_IS_RPC_PUT_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_PUT_ARGS))
#define THRIFT_RPC_PUT_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_PUT_ARGS, ThriftRpcPutArgsClass))

/* struct RpcPutResult */
struct _ThriftRpcPutResult
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _ThriftRpcPutResult ThriftRpcPutResult;

struct _ThriftRpcPutResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcPutResultClass ThriftRpcPutResultClass;

GType thrift_rpc_put_result_get_type (void);
#define THRIFT_TYPE_RPC_PUT_RESULT (thrift_rpc_put_result_get_type())
#define THRIFT_RPC_PUT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_PUT_RESULT, ThriftRpcPutResult))
#define THRIFT_RPC_PUT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_PUT_RESULT, ThriftRpcPutResultClass))
#define THRIFT_IS_RPC_PUT_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_PUT_RESULT))
#define THRIFT_IS_RPC_PUT_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_PUT_RESULT))
#define THRIFT_RPC_PUT_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_PUT_RESULT, ThriftRpcPutResultClass))

/* struct RpcPutLatestArgs */
struct _ThriftRpcPutLatestArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
  gint64 search_key;
  gboolean __isset_search_key;
  GByteArray * value;
  gboolean __isset_value;
};
typedef struct _ThriftRpcPutLatestArgs ThriftRpcPutLatestArgs;

struct _ThriftRpcPutLatestArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcPutLatestArgsClass ThriftRpcPutLatestArgsClass;

GType thrift_rpc_put_latest_args_get_type (void);
#define THRIFT_TYPE_RPC_PUT_LATEST_ARGS (thrift_rpc_put_latest_args_get_type())
#define THRIFT_RPC_PUT_LATEST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_PUT_LATEST_ARGS, ThriftRpcPutLatestArgs))
#define THRIFT_RPC_PUT_LATEST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_PUT_LATEST_ARGS, ThriftRpcPutLatestArgsClass))
#define THRIFT_IS_RPC_PUT_LATEST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_PUT_LATEST_ARGS))
#define THRIFT_IS_RPC_PUT_LATEST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_PUT_LATEST_ARGS))
#define THRIFT_RPC_PUT_LATEST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_PUT_LATEST_ARGS, ThriftRpcPutLatestArgsClass))

/* struct RpcPutLatestResult */
struct _ThriftRpcPutLatestResult
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _ThriftRpcPutLatestResult ThriftRpcPutLatestResult;

struct _ThriftRpcPutLatestResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcPutLatestResultClass ThriftRpcPutLatestResultClass;

GType thrift_rpc_put_latest_result_get_type (void);
#define THRIFT_TYPE_RPC_PUT_LATEST_RESULT (thrift_rpc_put_latest_result_get_type())
#define THRIFT_RPC_PUT_LATEST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_PUT_LATEST_RESULT, ThriftRpcPutLatestResult))
#define THRIFT_RPC_PUT_LATEST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_PUT_LATEST_RESULT, ThriftRpcPutLatestResultClass))
#define THRIFT_IS_RPC_PUT_LATEST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_PUT_LATEST_RESULT))
#define THRIFT_IS_RPC_PUT_LATEST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_PUT_LATEST_RESULT))
#define THRIFT_RPC_PUT_LATEST_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_PUT_LATEST_RESULT, ThriftRpcPutLatestResultClass))

/* struct RpcAddArgs */
struct _ThriftRpcAddArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
  ThriftBucketValue * value;
  gboolean __isset_value;
  gchar * name;
  gboolean __isset_name;
  gint64 search_key_min;
  gboolean __isset_search_key_min;
  gint64 search_key_max;
  gboolean __isset_search_key_max;
};
typedef struct _ThriftRpcAddArgs ThriftRpcAddArgs;

struct _ThriftRpcAddArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcAddArgsClass ThriftRpcAddArgsClass;

GType thrift_rpc_add_args_get_type (void);
#define THRIFT_TYPE_RPC_ADD_ARGS (thrift_rpc_add_args_get_type())
#define THRIFT_RPC_ADD_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_ADD_ARGS, ThriftRpcAddArgs))
#define THRIFT_RPC_ADD_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_ADD_ARGS, ThriftRpcAddArgsClass))
#define THRIFT_IS_RPC_ADD_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_ADD_ARGS))
#define THRIFT_IS_RPC_ADD_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_ADD_ARGS))
#define THRIFT_RPC_ADD_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_ADD_ARGS, ThriftRpcAddArgsClass))

/* struct RpcAddResult */
struct _ThriftRpcAddResult
{ 
  ThriftStruct parent; 

  /* public */
  ThriftStorageException * err;
  gboolean __isset_err;
};
typedef struct _ThriftRpcAddResult ThriftRpcAddResult;

struct _ThriftRpcAddResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcAddResultClass ThriftRpcAddResultClass;

GType thrift_rpc_add_result_get_type (void);
#define THRIFT_TYPE_RPC_ADD_RESULT (thrift_rpc_add_result_get_type())
#define THRIFT_RPC_ADD_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_ADD_RESULT, ThriftRpcAddResult))
#define THRIFT_RPC_ADD_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_ADD_RESULT, ThriftRpcAddResultClass))
#define THRIFT_IS_RPC_ADD_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_ADD_RESULT))
#define THRIFT_IS_RPC_ADD_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_ADD_RESULT))
#define THRIFT_RPC_ADD_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_ADD_RESULT, ThriftRpcAddResultClass))

/* struct RpcGetArgs */
struct _ThriftRpcGetArgs
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * key;
  gboolean __isset_key;
};
typedef struct _ThriftRpcGetArgs ThriftRpcGetArgs;

struct _ThriftRpcGetArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetArgsClass ThriftRpcGetArgsClass;

GType thrift_rpc_get_args_get_type (void);
#define THRIFT_TYPE_RPC_GET_ARGS (thrift_rpc_get_args_get_type())
#define THRIFT_RPC_GET_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_ARGS, ThriftRpcGetArgs))
#define THRIFT_RPC_GET_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_ARGS, ThriftRpcGetArgsClass))
#define THRIFT_IS_RPC_GET_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_ARGS))
#define THRIFT_IS_RPC_GET_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_ARGS))
#define THRIFT_RPC_GET_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_ARGS, ThriftRpcGetArgsClass))

/* struct RpcGetResult */
struct _ThriftRpcGetResult
{ 
  ThriftStruct parent; 

  /* public */
  GByteArray * success;
  gboolean __isset_success;
  ThriftStorageException * err;
  gboolean __isset_err;
};
typedef struct _ThriftRpcGetResult ThriftRpcGetResult;

struct _ThriftRpcGetResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetResultClass ThriftRpcGetResultClass;

GType thrift_rpc_get_result_get_type (void);
#define THRIFT_TYPE_RPC_GET_RESULT (thrift_rpc_get_result_get_type())
#define THRIFT_RPC_GET_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_RESULT, ThriftRpcGetResult))
#define THRIFT_RPC_GET_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_RESULT, ThriftRpcGetResultClass))
#define THRIFT_IS_RPC_GET_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_RESULT))
#define THRIFT_IS_RPC_GET_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_RESULT))
#define THRIFT_RPC_GET_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_RESULT, ThriftRpcGetResultClass))

/* struct RpcGetLatestMaxArgs */
struct _ThriftRpcGetLatestMaxArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * name;
  gboolean __isset_name;
  gint64 search_key_max;
  gboolean __isset_search_key_max;
};
typedef struct _ThriftRpcGetLatestMaxArgs ThriftRpcGetLatestMaxArgs;

struct _ThriftRpcGetLatestMaxArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetLatestMaxArgsClass ThriftRpcGetLatestMaxArgsClass;

GType thrift_rpc_get_latest_max_args_get_type (void);
#define THRIFT_TYPE_RPC_GET_LATEST_MAX_ARGS (thrift_rpc_get_latest_max_args_get_type())
#define THRIFT_RPC_GET_LATEST_MAX_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_ARGS, ThriftRpcGetLatestMaxArgs))
#define THRIFT_RPC_GET_LATEST_MAX_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_LATEST_MAX_ARGS, ThriftRpcGetLatestMaxArgsClass))
#define THRIFT_IS_RPC_GET_LATEST_MAX_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_ARGS))
#define THRIFT_IS_RPC_GET_LATEST_MAX_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_LATEST_MAX_ARGS))
#define THRIFT_RPC_GET_LATEST_MAX_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_ARGS, ThriftRpcGetLatestMaxArgsClass))

/* struct RpcGetLatestMaxResult */
struct _ThriftRpcGetLatestMaxResult
{ 
  ThriftStruct parent; 

  /* public */
  ThriftBucketValue * success;
  gboolean __isset_success;
  ThriftStorageException * err;
  gboolean __isset_err;
};
typedef struct _ThriftRpcGetLatestMaxResult ThriftRpcGetLatestMaxResult;

struct _ThriftRpcGetLatestMaxResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetLatestMaxResultClass ThriftRpcGetLatestMaxResultClass;

GType thrift_rpc_get_latest_max_result_get_type (void);
#define THRIFT_TYPE_RPC_GET_LATEST_MAX_RESULT (thrift_rpc_get_latest_max_result_get_type())
#define THRIFT_RPC_GET_LATEST_MAX_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_RESULT, ThriftRpcGetLatestMaxResult))
#define THRIFT_RPC_GET_LATEST_MAX_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_LATEST_MAX_RESULT, ThriftRpcGetLatestMaxResultClass))
#define THRIFT_IS_RPC_GET_LATEST_MAX_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_RESULT))
#define THRIFT_IS_RPC_GET_LATEST_MAX_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_LATEST_MAX_RESULT))
#define THRIFT_RPC_GET_LATEST_MAX_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_LATEST_MAX_RESULT, ThriftRpcGetLatestMaxResultClass))

/* struct RpcGetRangeArgs */
struct _ThriftRpcGetRangeArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * name;
  gboolean __isset_name;
  gint64 search_key_min;
  gboolean __isset_search_key_min;
  gint64 search_key_max;
  gboolean __isset_search_key_max;
};
typedef struct _ThriftRpcGetRangeArgs ThriftRpcGetRangeArgs;

struct _ThriftRpcGetRangeArgsClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetRangeArgsClass ThriftRpcGetRangeArgsClass;

GType thrift_rpc_get_range_args_get_type (void);
#define THRIFT_TYPE_RPC_GET_RANGE_ARGS (thrift_rpc_get_range_args_get_type())
#define THRIFT_RPC_GET_RANGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_RANGE_ARGS, ThriftRpcGetRangeArgs))
#define THRIFT_RPC_GET_RANGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_RANGE_ARGS, ThriftRpcGetRangeArgsClass))
#define THRIFT_IS_RPC_GET_RANGE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_RANGE_ARGS))
#define THRIFT_IS_RPC_GET_RANGE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_RANGE_ARGS))
#define THRIFT_RPC_GET_RANGE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_RANGE_ARGS, ThriftRpcGetRangeArgsClass))

/* struct RpcGetRangeResult */
struct _ThriftRpcGetRangeResult
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * success;
  gboolean __isset_success;
};
typedef struct _ThriftRpcGetRangeResult ThriftRpcGetRangeResult;

struct _ThriftRpcGetRangeResultClass
{
  ThriftStructClass parent;
};
typedef struct _ThriftRpcGetRangeResultClass ThriftRpcGetRangeResultClass;

GType thrift_rpc_get_range_result_get_type (void);
#define THRIFT_TYPE_RPC_GET_RANGE_RESULT (thrift_rpc_get_range_result_get_type())
#define THRIFT_RPC_GET_RANGE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_TYPE_RPC_GET_RANGE_RESULT, ThriftRpcGetRangeResult))
#define THRIFT_RPC_GET_RANGE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT__TYPE_RPC_GET_RANGE_RESULT, ThriftRpcGetRangeResultClass))
#define THRIFT_IS_RPC_GET_RANGE_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_TYPE_RPC_GET_RANGE_RESULT))
#define THRIFT_IS_RPC_GET_RANGE_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_TYPE_RPC_GET_RANGE_RESULT))
#define THRIFT_RPC_GET_RANGE_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_TYPE_RPC_GET_RANGE_RESULT, ThriftRpcGetRangeResultClass))

#endif /* THRIFT_RPC_TYPES_H */
